version: "3.8"
services:
  lovemap:
    image: docker.io/attilapalfi92/lovemap-backend:latest
    environment:
      spring_profiles_active: local
    ports:
      - "127.0.0.1:8090:8090"
    networks:
      - lovemap_network

  postgres:
    image: postgres:alpine # use latest official postgres version
    env_file:
      - postgres.env # configure postgres
    volumes:
      - lovemap_postgres_data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - lovemap_network
    ports:
      - "5432:5432"

volumes:
  lovemap_postgres_data: # named volumes can be managed easier using docker-compose
    name: lovemap_postgres_data

networks:
  lovemap_network:
    name: lovemap_network