version: "3.8"
services:
  postgres:
    image: postgres:alpine # use latest official postgres version
    env_file:
      - postgres.env # configure postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - lovemap_postgres_data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - lovemap_network
    ports:
      - 5432:5432

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

volumes:
  lovemap_postgres_data: # named volumes can be managed easier using docker-compose
    name: lovemap_postgres_data

networks:
  lovemap_network:
    name: lovemap_network