server:
  port: 8090

management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: info, health, metrics, prometheus

spring:
  cloud.gcp.metrics.enabled: false
  profiles:
    active: dev
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/lovemap
    user: changethis
    password: changethis
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/lovemap
    username: changethis
    password: changethis
    initial-size: 5
    pool:
      enabled: true
      max-size: 10
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost/lovemap?retryWrites=true&w=majority

springdoc:
  packagesToScan: com.lovemap.lovemapbackend
  pathsToMatch: /**

logging:
  file: lovemap.log
  level:
    root: INFO
    com.lovemap: INFO
    org.springframework.r2dbc: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.flywaydb: DEBUG


lovemap:
  admins:
    emails: ""

  signingKey: "overwrite this signing key in production"
  google:
    apiKey: "overwrite this apiKey key in production"
    projectId: "overwrite this"
    publicPhotosBucket: "overwrite this"

  facebook:
    appId: "overwrite this"
    appSecret: "overwrite this"

  clients:
    - id: dummy
      secret: dummy

  lovespot:
    photos:
      supportedFormats: jpg, jpeg, heic, heif, png

    risks:
      levels: 3
      riskList:
        - level: 1
          nameEN: Safe
          nameHU: Biztonságos
        - level: 2
          nameEN: Little risky
          nameHU: Kicsit kockázatos
        - level: 3
          nameEN: Very risky
          nameHU: Nagyon kockázatos

  lover:
    points:
      reviewSubmitted: 1
      reviewReceived4Stars: 1
      reviewReceived5Stars: 2
      reportSubmitted: 1
      reportReceived: -2
      loveSpotAdded: 5
      loveMade: 1
      photoUploaded: 5
      photoLikeReceived: 1
      photoDislikeReceived: -1
      pointsForFollower: 10

    ranks:
      rankList:
        - rank: 1
          nameEN: Loviner
          nameHU: Kezdő Leves
          pointsNeeded: 0
        - rank: 2
          nameEN: Lavurious
          nameHU: Érdeklődő Lover
          pointsNeeded: 10
        - rank: 3
          nameEN: Lovesperienced
          nameHU: Tapasztalt Lover
          pointsNeeded: 20
        - rank: 4
          nameEN: Lovespert
          nameHU: Szakértő Lover
          pointsNeeded: 40
        - rank: 5
          nameEN: Love Priest
          nameHU: Love Pap
          pointsNeeded: 60
        - rank: 6
          nameEN: Love Bishop
          nameHU: Love Püspök
          pointsNeeded: 100
        - rank: 7
          nameEN: Love Archbishop
          nameHU: Love Érsek
          pointsNeeded: 200
        - rank: 8
          nameEN: Love Cardinal
          nameHU: Love Bíboros
          pointsNeeded: 300
        - rank: 9
          nameEN: Love Pope
          nameHU: Love Pápa
          pointsNeeded: 500
        - rank: 10
          nameEN: Love God
          nameHU: Love Isten
          pointsNeeded: 1000
