server:
  port: 8090

lovemap:
  admins:
    emails: ""

  signingKey: "overwrite this signing key in production"

  lovespot:
    risks:
      levels: 3
      riskList:
        - level: 1
          nameEN: Safe
          nameHU: Biztonságos
        - level: 2
          nameEN: Little risky
          nameHU: Kicsit kockázatos
        - level: 3
          nameEN: Very risky
          nameHU: Nagyon kockázatos

  lover:
    points:
      reviewSubmitted: 1
      reviewReceived4Stars: 1
      reviewReceived5Stars: 2
      reportSubmitted: 1
      reportReceived: -2
      loveSpotAdded: 5
      loveMade: 1

    ranks:
      rankList:
        - rank: 1
          nameEN: Loviner
          nameHU: Kezdő Leves
          pointsNeeded: 0
        - rank: 2
          nameEN: Lavurious
          nameHU: Érdeklődő Lover
          pointsNeeded: 5
        - rank: 3
          nameEN: Lovesperienced
          nameHU: Tapasztalt Lover
          pointsNeeded: 10
        - rank: 4
          nameEN: Lovespert
          nameHU: Szakértő Lover
          pointsNeeded: 20
        - rank: 5
          nameEN: Love Priest
          nameHU: Love Pap
          pointsNeeded: 30
        - rank: 6
          nameEN: Love Bishop
          nameHU: Love Püspök
          pointsNeeded: 40
        - rank: 7
          nameEN: Love Archbishop
          nameHU: Love Érsek
          pointsNeeded: 50
        - rank: 8
          nameEN: Love Cardinal
          nameHU: Love Bíboros
          pointsNeeded: 60
        - rank: 9
          nameEN: Love Pope
          nameHU: Love Pápa
          pointsNeeded: 70
        - rank: 10
          nameEN: Love God
          nameHU: Love Isten
          pointsNeeded: 100

spring:
  profiles:
    active: dev
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  packagesToScan: com.lovemap.lovemapbackend
  pathsToMatch: /**

logging:
  level:
    root: INFO
    com.lovemap: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.security: INFO
    org.springframework.web: DEBUG
    org.flywaydb: DEBUG
