lovemap:
  signingKey: "overwrite this"

spring:
  flyway:
    url: jdbc:postgresql://10.41.113.3:5432/lovemap
    user: postgres
    password: X?oEmNic?l.r6:Dg
  r2dbc:
    url: r2dbc:postgresql://10.41.113.3:5432/lovemap
    username: postgres
    password: X?oEmNic?l.r6:Dg
