spring:
  flyway:
    url: jdbc:postgresql://34.118.100.193:5432/smackmap
    user: postgres
    password: ybfyBJcMgwPhmPh4
  r2dbc:
    url: r2dbc:postgresql://34.118.100.193:5432/smackmap
    username: postgres
    password: ybfyBJcMgwPhmPh4
