spring:
  flyway:
    url: jdbc:postgresql://10.41.113.3:5432/lovemap-test
    user: postgres
    password: X?oEmNic?l.r6:Dg
  r2dbc:
    url: r2dbc:postgresql://10.41.113.3:5432/lovemap-test
    username: postgres
    password: X?oEmNic?l.r6:Dg
