apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: lovemap-hc-config
spec:
  timeoutSec: 300
  logging:
    enable: true
    sampleRate: 1
  healthCheck:
    healthyThreshold: 1
    unhealthyThreshold: 5
    checkIntervalSec: 15
    port: 8090
    type: HTTP
    requestPath: /join-us.html