apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: lovemap-hc-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8090
    type: HTTP
    requestPath: /privacy-policy.html