ALTER TABLE lover ADD COLUMN rank SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE lover ADD COLUMN points INTEGER NOT NULL DEFAULT 0;
ALTER TABLE lover ADD COLUMN number_of_loves INTEGER NOT NULL DEFAULT 0;
ALTER TABLE lover ADD COLUMN number_of_reports INTEGER NOT NULL DEFAULT 0;
ALTER TABLE lover ADD COLUMN love_spots_added INTEGER NOT NULL DEFAULT 0;
ALTER TABLE lover ADD COLUMN number_of_followers INTEGER NOT NULL DEFAULT 0;
ALTER TABLE lover ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
