ALTER TABLE smacker ADD COLUMN rank SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE smacker ADD COLUMN points INTEGER NOT NULL DEFAULT 0;
ALTER TABLE smacker ADD COLUMN number_of_smacks INTEGER NOT NULL DEFAULT 0;
ALTER TABLE smacker ADD COLUMN number_of_reports INTEGER NOT NULL DEFAULT 0;
ALTER TABLE smacker ADD COLUMN smack_spots_added INTEGER NOT NULL DEFAULT 0;
ALTER TABLE smacker ADD COLUMN number_of_followers INTEGER NOT NULL DEFAULT 0;
ALTER TABLE smacker ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
